# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_optional.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/functional_test_data.rb'
    - 'db/schema.rb'
    - 'bin/*'

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

Style/Encoding:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
    - 'app/admin/*'
    - 'Guardfile'

Style/DoubleNegation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/UselessAssignment:
   Exclude:
    - 'app/models/cv_item.rb'

Naming/AccessorMethodName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"