
Metrics/AbcSize:
  Max: 60

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/MethodLength:
  Max: 200

Metrics/ModuleLength:
  Max: 500

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 50

Style/Documentation:
  Enabled: false

