source 'https://rubygems.org'
ruby '2.4.1'

gem 'activeadmin'
gem 'activerecord-reputation-system'
gem 'cancan'
gem 'capistrano', '~> 3.7', '>= 3.7.1'
gem 'capistrano-passenger', '~> 0.2.0'
gem 'capistrano-rails', '~> 1.2'
gem 'capistrano-rbenv', '~> 2.1'
gem 'carrierwave', '~> 1.1.0'
gem 'carrierwave-i18n'
gem 'carrierwave-unoconv'
gem 'coffee-rails', '~> 4.2'
gem 'decent_exposure'
gem 'devise'
gem 'devise-i18n'
gem 'factory_girl_rails'
gem 'faker', '~> 1.7.3'
gem 'fog-aws'
gem 'font-awesome-rails'
gem 'foundation_emails'
gem 'foundation-rails'
gem 'friendly_id'
gem 'gretel'
gem 'haml-rails', '~> 0.9'
gem 'inky-rb', require: 'inky'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'kaminari-i18n'
gem 'mini_magick'
gem 'offsite_payments'
gem 'pg', '~> 0.18'
gem 'premailer-rails'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.2'
gem 'rails-i18n'
gem 'rails-jquery-autocomplete'
gem 'redcarpet'
gem 'sass-rails', '~> 5.0'
gem 'simple_form'
gem 'turbolinks', '~> 5'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'binding_of_caller'
  gem 'byebug', platform: :mri
  gem 'pry'
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
end

group :development do
  gem 'db_fixtures_dump'
  gem 'guard-livereload'
  gem 'guard-rspec', require: false
  gem 'listen', '~> 3.0.5'
  gem 'meta_request'
  gem 'seed_dump'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end
